from Simulation import Morphology

NUM_OF_NODES_RANGE = (3, 10)
MASS_OF_NODES_RANGE = (5, 2000)
RADIUS_OF_NODES_RANGE = (5, 20)
SPRING_CONSTANT_RANGE = (5000, 10000)
SPRING_DAMPING_RANGE = (1000, 10000)
AMPLITUDE_OF_ACTUATION_RANGE = (1000, 10000)
D_ACTUATE_RANGE = (1, 5)
MASS_ARRANGEMENT_STRATS = (
    Morphology.MASS_ARRANGEMENT_GEOMETRIC_WITHOUT_CENTER,
    Morphology.MASS_ARRANGEMENT_GEOMETRIC_WITH_CENTER,
    Morphology.MASS_ARRANGEMENT_LINEAR_TRIANGULATION,
    Morphology.MASS_ARRANGEMENT_OMNIDIRECTIONAL_TRIANGULATION
)

K_RANGE = (-10, 10)
OMEGA_RANGE = (1, 10)

ALPHA_BETA_RANGE = (1, 50)
